# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Yaseen
email: myaseen.khan@hotmial.com
description: "A blog maybe or may be some weird sh!t who knows? :-D"
baseurl: "" # the subpath of your site, e.g. /blog
url: "foxt7ot.github.io" # the base hostname & protocol for your site
twitter_username: foxt7ot
github_username:  foxt7ot

gems: [jekyll-paginate]

# Site settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

timezone: Asia/Kolkata

permalink: :slug.html

# Paginate
paginate: 7
paginate_path: "/page-:num/"

# Exclude
exclude: [scripts/, README.md, Gemfile, Gemfile.lock]

# Tags
tag_page_layout: tag_page
tag_feed_layout: tag_feed
tag_page_dir: tag
tag_feed_dir: tag
